## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter");'
  - julia -e 'using Pkg; cd(Pkg.dir("IntervalMatrices")); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("IntervalMatrices")); using Coverage; Codecov.submit(Codecov.process_folder())'
