[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[compat]
Documenter = "1"
IntervalArithmetic = "0.21, =0.21"  # v0.22 changed the output format
